### ISSUE TITLE
Card title

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/dumi-theme-alita#15]
![image](https://user-images.githubusercontent.com/11746742/113798705-47be5580-9786-11eb-91ae-33d325a733fa.png)

**Comment by hang1017** [comment]
fix: https://github.com/alitajs/dumi-theme-alita/pull/16
branch already merged to master

**Comment by hang1017** [comment]
@xiaohuoni

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/dumi-theme-alita/pull/16
